---
# tasks file for roles/nginx-role
- name: create the /tmp/nginx directory on the host
#  become: true
#  become_method: sudo
  file:
    path: /tmp/nginx
    state: 'directory'
    mode: '0755'

- name: put the nginx.conf file in place
#  become: true
#  become_method: sudo
  template:
    src: nginx.conf.j2
    dest: /tmp/nginx/nginx.conf

- name: start the nginx docker container
#  become: true
#  become_method: sudo
  docker_container:
    image: "nginx:{{ nginx_tag }}"
    name: "{{ nginx_container_name }}"
    ports: '{{ nginx_published_ports }}'
    exposed_ports: '{{ nginx_exposed_ports }}'
    state: 'started'
    networks:
      - name: containers_net
    restart_policy: 'always'
    log_driver: 'syslog'
    log_options:
      tag: "{{ nginx_container_name }}"
      
- name: copy template in the container
  command: docker cp /tmp/nginx/nginx.conf '{{ nginx_container_name }}':/etc/nginx/nginx.conf
#  become: yes
#  become_method: sudo
